# See config.example.yml for documentation.
name: oot-gc
object_base: orig/mq-u
object: files/zlj_f.tgc:sys/main.dol
hash: 1bd1d5e7c13dc94c2090d458c9e6706932e611a8
symbols: config/mq-u/symbols.txt
splits: config/mq-u/splits.txt
mw_comment_version: 8

extract:
# xlCoreGCN.c
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
# simGCN.c
- symbol: gcoverOpen
  header: gcoverOpen.inc
- symbol: gnoDisk
  header: gnoDisk.inc
- symbol: gretryErr
  header: gretryErr.inc
- symbol: gfatalErr
  header: gfatalErr.inc
- symbol: gwrongDisk
  header: gwrongDisk.inc
- symbol: greadingDisk
  header: greadingDisk.inc
- symbol: gbar
  header: gbar.inc
- symbol: gyes
  header: gyes.inc
- symbol: gno
  header: gno.inc
- symbol: gmesgOK
  header: gmesgOK.inc

block_relocations:
# systemSetupGameALL
- source: 0x8002E128
- source: 0x8002E134
- source: 0x8002E154
- source: 0x8002E15C
- source: 0x8002E17C
- source: 0x8002E188
- source: 0x8002E1A8
- source: 0x8002E1B0
- source: 0x8002E204
- source: 0x8002E20C
- source: 0x8002E22C
- source: 0x8002E24C
- source: 0x8002E258
- source: 0x8002E27C
- source: 0x8002E76C
- source: 0x8002E774
- source: 0x8002E79C
- source: 0x8002E7C4
- source: 0x8002E7EC
- source: 0x8002E814
- source: 0x8002E83C
- source: 0x8002E864
- source: 0x8002E88C
- source: 0x8002E8B4
- source: 0x8002E8D8
- source: 0x8002E8FC
- source: 0x8002EBD8
- source: 0x8002EBE4
- source: 0x8002ECF8
- source: 0x8002ED04
- source: 0x8002EDEC
- source: 0x8002EDF4
- source: 0x8002EE18
- source: 0x8002EE3C
- source: 0x8002EE60
- source: 0x8002EE68
- source: 0x8002EE8C
- source: 0x8002EEB0
- source: 0x8002EFE4
- source: 0x8002EFF0
- source: 0x8002F018
- source: 0x8002F040
- source: 0x8002F074
- source: 0x8002F080
- source: 0x8002F0A4
- source: 0x8002F0D0
- source: 0x8002F104
- source: 0x8002F110
- source: 0x8002F134
- source: 0x8002F154
- source: 0x8002F160
- source: 0x8002F2C0
- source: 0x8002F2CC
- source: 0x8002F2F4
- source: 0x8002F840
- source: 0x8002F84C
- source: 0x8002F874
- source: 0x8002F89C
- source: 0x8002F8C0
- source: 0x8002F8E8
- source: 0x8002FA68
- source: 0x8002FA74
- source: 0x8002FAD4
- source: 0x8002FADC
- source: 0x8002FB00
- source: 0x8002FB20
- source: 0x8002FB2C
- source: 0x8002FB50
- source: 0x8002FC30
- source: 0x8002FC40
- source: 0x8002FD84
- source: 0x8002FD90
- source: 0x8002FDC8
- source: 0x8002FDD8
- source: 0x8002FF04
- source: 0x8002FF0C
- source: 0x8002FF44
- source: 0x8002FF54
- source: 0x8002FF7C
# cpuFindFunction
- source: 0x8003342C
- source: 0x80033434
- source: 0x80033440
- source: 0x80033BD0
- source: 0x80033C00
- source: 0x80033C04
- source: 0x80033C38
- source: 0x80033C4C
- source: 0x80033C8C
- source: 0x80033C90
- source: 0x80033CC4
- source: 0x80033CD8
