#include "stdio.h"

extern int __read_console(__file_handle file, unsigned char* buff, size_t* count, __idle_proc idle_proc);
extern int __write_console(__file_handle file, unsigned char* buff, size_t* count, __idle_proc idle_proc);
extern int __close_console(__file_handle file);

FILE __files[3] = {
    {
        0,
        {0, 1, 0, __console_file, 0, __neutral},
        {0, 0, 0, 0},
        0,
        0,
        {0},
        {0},
        0,
        &__files[0].char_buffer,
        1,
        &__files[0].char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        &__read_console,
        &__write_console,
        &__close_console,
        NULL,
    },
    {
        0,
        {0, 2, 0, __console_file, 0, __neutral},
        {0, 0, 0, 0},
        0,
        0,
        {0},
        {0},
        0,
        &__files[1].char_buffer,
        1,
        &__files[1].char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        &__read_console,
        &__write_console,
        &__close_console,
        NULL,
    },
    {
        0,
        {0, 2, 0, __console_file, 0, __neutral},
        {0, 0, 0, 0},
        0,
        0,
        {0},
        {0},
        0,
        &__files[2].char_buffer,
        1,
        &__files[2].char_buffer,
        0,
        0,
        0,
        0,
        NULL,
        &__read_console,
        &__write_console,
        &__close_console,
        NULL,
    },
};
