# See config.example.yml for documentation.
name: oot-gc
object_base: orig/ce-e
object: files/tgc/zelda_PAL_093003.tgc:sys/main.dol
hash: 8c5c365ae2df34c4cb27e86eb1cf30f2a2e4cd1b
symbols: config/ce-e/symbols.txt
splits: config/ce-e/splits.txt
mw_comment_version: 8

extract:
# xlCoreGCN.c
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
# simGCN.c
- symbol: gcoverOpen
  header: gcoverOpen.inc
- symbol: gnoDisk
  header: gnoDisk.inc
- symbol: gretryErr
  header: gretryErr.inc
- symbol: gfatalErr
  header: gfatalErr.inc
- symbol: gwrongDisk
  header: gwrongDisk.inc
- symbol: greadingDisk
  header: greadingDisk.inc
- symbol: gyes
  header: gyes.inc
- symbol: gno
  header: gno.inc
- symbol: gmesgOK
  header: gmesgOK.inc
- symbol: gfrench_coverOpen
  header: gfrench_coverOpen.inc
- symbol: gfrench_noDisk
  header: gfrench_noDisk.inc
- symbol: gfrench_retryErr
  header: gfrench_retryErr.inc
- symbol: gfrench_fatalErr
  header: gfrench_fatalErr.inc
- symbol: gfrench_wrongDisk
  header: gfrench_wrongDisk.inc
- symbol: gfrench_readingDisk
  header: gfrench_readingDisk.inc
- symbol: gfrench_yes
  header: gfrench_yes.inc
- symbol: gfrench_no
  header: gfrench_no.inc
- symbol: gfrench_mesgOK
  header: gfrench_mesgOK.inc
- symbol: ggerman_coverOpen
  header: ggerman_coverOpen.inc
- symbol: ggerman_noDisk
  header: ggerman_noDisk.inc
- symbol: ggerman_retryErr
  header: ggerman_retryErr.inc
- symbol: ggerman_fatalErr
  header: ggerman_fatalErr.inc
- symbol: ggerman_wrongDisk
  header: ggerman_wrongDisk.inc
- symbol: ggerman_readingDisk
  header: ggerman_readingDisk.inc
- symbol: ggerman_yes
  header: ggerman_yes.inc
- symbol: ggerman_no
  header: ggerman_no.inc
- symbol: ggerman_mesgOK
  header: ggerman_mesgOK.inc
- symbol: gspanish_coverOpen
  header: gspanish_coverOpen.inc
- symbol: gspanish_noDisk
  header: gspanish_noDisk.inc
- symbol: gspanish_retryErr
  header: gspanish_retryErr.inc
- symbol: gspanish_fatalErr
  header: gspanish_fatalErr.inc
- symbol: gspanish_wrongDisk
  header: gspanish_wrongDisk.inc
- symbol: gspanish_readingDisk
  header: gspanish_readingDisk.inc
- symbol: gspanish_yes
  header: gspanish_yes.inc
- symbol: gspanish_no
  header: gspanish_no.inc
- symbol: gspanish_mesgOK
  header: gspanish_mesgOK.inc
- symbol: gitalian_coverOpen
  header: gitalian_coverOpen.inc
- symbol: gitalian_noDisk
  header: gitalian_noDisk.inc
- symbol: gitalian_retryErr
  header: gitalian_retryErr.inc
- symbol: gitalian_fatalErr
  header: gitalian_fatalErr.inc
- symbol: gitalian_wrongDisk
  header: gitalian_wrongDisk.inc
- symbol: gitalian_readingDisk
  header: gitalian_readingDisk.inc
- symbol: gitalian_yes
  header: gitalian_yes.inc
- symbol: gitalian_no
  header: gitalian_no.inc
- symbol: gitalian_mesgOK
  header: gitalian_mesgOK.inc
- symbol: gbar
  header: gbar.inc
# rom.c
- symbol: ganOffsetBlock_ZLP
  header: ganOffsetBlock_ZLP.inc
- symbol: ganOffsetBlock_URAZLP
  header: ganOffsetBlock_URAZLP.inc

block_relocations:
# system.c
- source: 0x8002E12C
- source: 0x8002E138
- source: 0x8002E158
- source: 0x8002E160
- source: 0x8002E194
- source: 0x8002E1A0
- source: 0x8002E1C0
- source: 0x8002E1C8
- source: 0x8002E1FC
- source: 0x8002E208
- source: 0x8002E228
- source: 0x8002E230
- source: 0x8002E284
- source: 0x8002E28C
- source: 0x8002E2AC
- source: 0x8002E2E0
- source: 0x8002E2EC
- source: 0x8002E310
- source: 0x8002E344
- source: 0x8002E350
- source: 0x8002E374
- source: 0x8002E8A8
- source: 0x8002E8B0
- source: 0x8002E8D0
- source: 0x8002E8D8
- source: 0x8002E900
- source: 0x8002E928
- source: 0x8002E950
- source: 0x8002E978
- source: 0x8002E9A0
- source: 0x8002E9C8
- source: 0x8002E9F0
- source: 0x8002EA18
- source: 0x8002EA3C
- source: 0x8002EA60
- source: 0x8002EA80
- source: 0x8002EA88
- source: 0x8002ED6C
- source: 0x8002ED78
- source: 0x8002EEA4
- source: 0x8002EEB0
- source: 0x8002EF98
- source: 0x8002EFA0
- source: 0x8002EFE8
- source: 0x8002F00C
- source: 0x8002F014
- source: 0x8002F038
- source: 0x8002F05C
- source: 0x8002F1A8
- source: 0x8002F1B4
- source: 0x8002F1DC
- source: 0x8002F204
- source: 0x8002F238
- source: 0x8002F244
- source: 0x8002F268
- source: 0x8002F294
- source: 0x8002F2C8
- source: 0x8002F2D4
- source: 0x8002F2F8
- source: 0x8002F318
- source: 0x8002F324
- source: 0x8002F49C
- source: 0x8002F4A8
- source: 0x8002F4D0
- source: 0x8002FA94
- source: 0x8002FAA0
- source: 0x8002FAC8
- source: 0x8002FAF0
- source: 0x8002FB14
- source: 0x8002FB3C
- source: 0x8002FCD4
- source: 0x8002FCE0
- source: 0x8002FD40
- source: 0x8002FD48
- source: 0x8002FD6C
- source: 0x8002FD8C
- source: 0x8002FD98
- source: 0x8002FDBC
- source: 0x8002FE9C
- source: 0x8002FEAC
- source: 0x80030008
- source: 0x80030014
- source: 0x8003004C
- source: 0x8003005C
- source: 0x800301A0
- source: 0x800301A8
- source: 0x800301E0
- source: 0x800301F0
- source: 0x80030218
# cpu.c
- source: 0x800336BC
- source: 0x800336C4
- source: 0x80033724
- source: 0x8003372C
- source: 0x80033738
- source: 0x80033EC8
- source: 0x80033EF8
- source: 0x80033EFC
- source: 0x80033F30
- source: 0x80033F44
- source: 0x80033F84
- source: 0x80033F88
- source: 0x80033FBC
- source: 0x80033FD0
